apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    component: fluentd
    logging-infra: fluentd
    provider: openshift
  name: logging-fluentd
spec:
  selector:
    matchLabels:
      component: fluentd
      provider: openshift
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: fluentd
        provider: openshift
      name: fluentd-elasticsearch
    spec:
      containers:
      - env:
        - name: K8S_HOST_URL
          value: https://kubernetes.default.svc.cluster.local
        - name: ES_HOST
          value: logging-es
        - name: ES_PORT
          value: "9200"
        - name: ES_CLIENT_CERT
          value: /etc/fluent/keys/cert
        - name: ES_CLIENT_KEY
          value: /etc/fluent/keys/key
        - name: ES_CA
          value: /etc/fluent/keys/ca
        - name: OPS_HOST
          value: logging-es
        - name: OPS_PORT
          value: "9200"
        - name: OPS_CLIENT_CERT
          value: /etc/fluent/keys/cert
        - name: OPS_CLIENT_KEY
          value: /etc/fluent/keys/key
        - name: OPS_CA
          value: /etc/fluent/keys/ca
        - name: ES_COPY
          value: "false"
        - name: ES_COPY_HOST
        - name: ES_COPY_PORT
        - name: ES_COPY_SCHEME
          value: https
        - name: ES_COPY_CLIENT_CERT
        - name: ES_COPY_CLIENT_KEY
        - name: ES_COPY_CA
        - name: ES_COPY_USERNAME
        - name: ES_COPY_PASSWORD
        - name: OPS_COPY_HOST
        - name: OPS_COPY_PORT
        - name: OPS_COPY_SCHEME
          value: https
        - name: OPS_COPY_CLIENT_CERT
        - name: OPS_COPY_CLIENT_KEY
        - name: OPS_COPY_CA
        - name: OPS_COPY_USERNAME
        - name: OPS_COPY_PASSWORD
        image: registry.dataos.io/openshift/origin-logging-fluentd:latest
        imagePullPolicy: Always
        name: fluentd-elasticsearch
        resources:
          limits:
            cpu: 100m
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /etc/fluent/keys
          name: certs
          readOnly: true
        - mountPath: /etc/docker-hostname
          name: dockerhostname
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        logging-infra-fluentd: "true"
      restartPolicy: Always
      securityContext: {}
      serviceAccount: aggregated-logging-fluentd
      serviceAccountName: aggregated-logging-fluentd
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
      - name: certs
        secret:
          secretName: logging-fluentd
      - hostPath:
          path: /etc/hostname
        name: dockerhostname
status:
  currentNumberScheduled: 16
  desiredNumberScheduled: 16
  numberMisscheduled: 0
